name: WebScraping

on:
  schedule:
    - cron: '5 * * * *'

  workflow_dispatch:

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python
        with:
          python-version: '3.x'
      - name: Install dependecies required
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  wbscp:
    name: Web Scraping
    needs: build
    runs-on: ubuntu-latest

    steps:
      - run: |
          cd Programa
          python main